
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: nginx-monitor
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # needs to match above matchLabels
    prometheus: nginx-monitor
  name: nginx-monitor
spec:
  endpoints:
  - interval: 15s
    port: prometheus
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: nginx-ingress-controller
  namespaceSelector:
    any: true